[tool.poetry]
name = "dj-test"
version = "0.1.0"
description = ""
authors = ["Roman <axeman.ofic@gmail.com>"]
readme = "README.md"
packages = [{include = "dj_test"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
